In [11]:
import numpy as np
import pandas as pd
import wget
from scipy.stats import binom

In [5]:
url = 'https://raw.githubusercontent.com/asegura4488/Database/main/MetodosComputacionalesReforma/BinomialCoins.csv'
wget.download(url,'Binomial.csv')

100% [....................................................................................] 49 / 49

'Binomial.csv'

In [7]:
data = pd.read_csv('Binomial.csv')
data

NCaras  ObsFreq
0       0       38
1       1      143
2       2      343
3       3      285
4       4      166
5       5       25

In [15]:
NCaras = np.array(data.NCaras)
ObsFreq = np.array(data.ObsFreq)
NCaras
ObsFreq

array([ 38, 143, 343, 285, 166,  25])

In [16]:
phat = np.sum(NCaras*ObsFreq)/(5000)
phat

0.4946

In [17]:
Exp = binom.pmf(NCaras,5,phat)
Exp

array([0.03297435, 0.16134855, 0.31580132, 0.30905289, 0.15122434,
       0.02959856])

In [18]:
FreqExp = Exp*1000
FreqExp

array([ 32.97434579, 161.34854994, 315.80131698, 309.05289153,
       151.22433731,  29.59855846])

In [19]:
ObsFreq

array([ 38, 143, 343, 285, 166,  25])

In [20]:
from scipy.stats import chi2

In [21]:
df = 6 - 1 - 1
df

4

In [24]:
chi2critico = chi2.ppf(0.95,df=df)
print(chi2critico)

9.487729036781154
