In [1]:
import numpy as np

In [2]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
print(M)
b = np.array([1.,3.,7.])
print(b)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]
[1. 3. 7.]


In [3]:
def GetGaussSeidel(A,b,x0,itmax = 100,error = 1e-10):
    
    M,N = A.shape
    x = x0
    
    residuo = np.linalg.norm(b - np.dot(A,x))
    it = 0
    
    while residuo > error and it < itmax:
        
        it += 1
        
        for i in range(M):
            
            sum_ = 0.
            
            for j in range(N):
                
                if i != j:
                    sum_ += A[i,j]*x[j]
                    
            x[i] = (b[i] - sum_)/A[i,i]
            
        print(x)
        residuo = np.linalg.norm(b - np.dot(A,x))
        
    return x,residuo,it

In [4]:
x0 = np.array([10.,-3.,4.])
Xsol, error, it = GetGaussSeidel(M,b,x0)

[ 0.66666667 -0.11111111  1.44444444]
[0.77777778 0.77777778 1.16666667]
[0.98148148 0.9382716  1.02469136]
[0.98765432 0.98765432 1.00925926]
[0.99897119 0.99657064 1.00137174]
[0.99931413 0.99931413 1.0005144 ]
[0.99994284 0.99980948 1.00007621]
[0.9999619  0.9999619  1.00002858]
[0.99999682 0.99998942 1.00000423]
[0.99999788 0.99999788 1.00000159]
[0.99999982 0.99999941 1.00000024]
[0.99999988 0.99999988 1.00000009]
[0.99999999 0.99999997 1.00000001]
[0.99999999 0.99999999 1.        ]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]


In [5]:
print(it)

18
